[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = [
    "python -m pip install -r requirements.txt",
    "PLAYWRIGHT_BROWSERS_PATH=/app/playwright_browsers python -m playwright install chromium"
]
